export const resizeHandleStyles = {
  top: {
    width: "8px",
    height: "8px",
    background: "#3b82f6",
    borderRadius: "1px",
    top: "-5px",
    left: "50%",
    transform: "translateX(-50%)",
    border: "2px solid transparent",
  },
  bottom: {
    width: "8px",
    height: "8px",
    background: "#3b82f6",
    borderRadius: "1px",
    bottom: "-5px",
    left: "50%",
    transform: "translateX(-50%)",
    border: "2px solid transparent",
  },
  left: {
    width: "8px",
    height: "8px",
    background: "#3b82f6",
    borderRadius: "1px",
    left: "-5px",
    top: "50%",
    transform: "translateY(-50%)",
    border: "2px solid transparent",
  },
  right: {
    width: "8px",
    height: "8px",
    background: "#3b82f6",
    borderRadius: "1px",
    right: "-5px",
    top: "50%",
    transform: "translateY(-50%)",
    border: "2px solid transparent",
  },
  topLeft: {
    width: "8px",
    height: "8px",
    background: "#3b82f6",
    borderRadius: "1px",
    top: "-4.5px",
    left: "-5px",
    border: "2px solid transparent",
  },
  topRight: {
    width: "8px",
    height: "8px",
    background: "#3b82f6",
    borderRadius: "1px",
    top: "-4.5px",
    right: "-5px",
    border: "2px solid transparent",
  },
  bottomLeft: {
    width: "8px",
    height: "8px",
    background: "#3b82f6",
    borderRadius: "1px",
    bottom: "-4.5px",
    left: "-5px",
    border: "2px solid transparent",
  },
  bottomRight: {
    width: "8px",
    height: "8px",
    background: "#3b82f6",
    borderRadius: "1px",
    bottom: "-4.5px",
    right: "-5px",
    border: "2px solid transparent",
  },
};
