export const resizeHandleStyles = {
  top: {
    width: "12px",
    height: "12px",
    background: "#3b82f6",
    border: "2px solid white",
    borderRadius: "2px",
    top: "-6px",
    left: "50%",
    transform: "translateX(-50%)",
  },
  bottom: {
    width: "12px",
    height: "12px",
    background: "#3b82f6",
    border: "2px solid white",
    borderRadius: "2px",
    bottom: "-6px",
    left: "50%",
    transform: "translateX(-50%)",
  },
  left: {
    width: "12px",
    height: "12px",
    background: "#3b82f6",
    border: "2px solid white",
    borderRadius: "2px",
    left: "-6px",
    top: "50%",
    transform: "translateY(-50%)",
  },
  right: {
    width: "12px",
    height: "12px",
    background: "#3b82f6",
    border: "2px solid white",
    borderRadius: "2px",
    right: "-6px",
    top: "50%",
    transform: "translateY(-50%)",
  },
  topLeft: {
    width: "12px",
    height: "12px",
    background: "#3b82f6",
    border: "2px solid white",
    borderRadius: "2px",
    top: "-6px",
    left: "-6px",
  },
  topRight: {
    width: "12px",
    height: "12px",
    background: "#3b82f6",
    border: "2px solid white",
    borderRadius: "2px",
    top: "-6px",
    right: "-6px",
  },
  bottomLeft: {
    width: "12px",
    height: "12px",
    background: "#3b82f6",
    border: "2px solid white",
    borderRadius: "2px",
    bottom: "-6px",
    left: "-6px",
  },
  bottomRight: {
    width: "12px",
    height: "12px",
    background: "#3b82f6",
    border: "2px solid white",
    borderRadius: "2px",
    bottom: "-6px",
    right: "-6px",
  },
};
